{% set version = "1.8.0" %}

package:
  name: ucc
  version: {{ version }}

source:
  url: https://github.com/openucx/ucc/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1fc0b7c5d6e5592ae1efff13705ff5cee2e67eba67914c2c70039e6854310b67

build:
  skip: true  # [(not linux) or cuda_compiler_version in (undefined, "None")]
  number: 3
  run_exports:
    - {{ pin_subpackage("ucc") }}
  missing_dso_whitelist:
    - '*libcuda.so*'
    - '*libcudart.so*'
    - '*libnvidia-ml.so*'
    - '*libnccl.so*'
  ignore_run_exports_from:
    - ucx
    # allow CPU-only use cases (xref: conda-forge/ucx-split-feedstock#173)
    - {{ compiler("cuda") }}
    - cuda-cudart-dev
    - nccl

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - automake
    - autoconf !=2.72  # work around conda-forge/autoconf-feedstock#41
    - libtool
    - make
  host:
    - ucx
    - rdma-core
    - cuda-version {{ cuda_compiler_version }}
    - cuda-cudart-dev
    - cuda-nvml-dev
    - nccl
  run:
    - {{ pin_compatible("ucx", max_pin="x.x.x") }}
  run_constrained:
    - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
    # The actual version constraint comes from cuda-version, so below we explicit list
    # them only to codify that these are expected (but optional) dependencies when CUDA
    # is in use, otherwise the solver gets confused (conda-forge/ucc-feedstock#19).
    - cuda-cudart
    - {{ pin_compatible("nccl", max_pin="x") }}

test:
  commands:
    - test -f $PREFIX/bin/ucc_info
    - test -f $PREFIX/include/ucc/api/ucc_def.h
    - test -f $PREFIX/include/ucc/api/ucc_status.h
    - test -f $PREFIX/include/ucc/api/ucc_version.h
    - test -f $PREFIX/include/ucc/api/ucc.h
    - test -f $PREFIX/lib/cmake/ucc/ucc-targets.cmake
    - test -f $PREFIX/lib/cmake/ucc/ucc-config-version.cmake
    - test -f $PREFIX/lib/cmake/ucc/ucc-config.cmake
    - test -f $PREFIX/lib/libucc.so.1
    - test -f $PREFIX/lib/ucc/libucc_mc_cuda.so.1
    - test -f $PREFIX/lib/ucc/libucc_mc_cpu.so.1
    - test -f $PREFIX/lib/ucc/libucc_tl_self.so.1
    - test -f $PREFIX/lib/ucc/libucc_tl_ucp.so.1
    - test -f $PREFIX/lib/ucc/libucc_cl_basic.so.1
    - test -f $PREFIX/lib/ucc/libucc_cl_hier.so.1
    - test -f $PREFIX/lib/ucc/libucc_ec_cuda.so.1
    - test -f $PREFIX/lib/ucc/libucc_ec_cpu.so.1
    - test -f $PREFIX/lib/ucc/libucc_sysinfo_cuda.so.1
    - test -f $PREFIX/lib/ucc/libucc_sysinfo_ib.so.1
    - test -f $PREFIX/bin/.ucc-post-link.sh


about:
  home: https://github.com/openucx/ucc
  summary: 'UCC is a collective communication operations API and library.'
  description: |
    UCC is a collective communication operations API and library that is
    flexible, complete, and feature-rich for current and emerging
    programming models and runtimes.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcinz
    - m3vaz
    - leofang
